[project]
name = "the-calcutorium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "moderngl>=5.12.0",
    "numpy>=2.4.2",
    "pyside6>=6.10.2",
    "sympy>=1.14.0",
]
